### ISSUE TITLE
Event participants : allow to call members in a specific group AND tag ?

### ISSUE THREAD

**Issue by kazemar** [kalisio/kdk#446] opened 2021-08-16 11:09 UTC
I create 2 groups : 
- **"Technical services"** with 5 members : Alpha, Bravo, Charlie, Delta and Echo.
- **"Communication cell"** with 3 members : Foxtrot, Golf and Hotel

I create a tag
- **"On-call duty"**, with 3 members : Bravo, Delta, and Hotel

I would like to create an event calling only the "On-call duty" from the "Technical services" : the event should allow me in this case to call only the 
**group="Technical services" AND tag="On-call duty"**
so I won't call for this event Hotel, who is "On-call duty" but in the "Communication cell"

-> Advantage : I can manage my "On-call duty" members without editing the different events I created

Edit : a bypass today consists to create a group, like "TS On-call duty" and associate members. The only problem is that I need such a group for each service using On-call duty.

**Comment by claustres** [comment] 2021-08-31 12:31
Maybe the problem is that you are mixing people that are "on-duty" but within different services, which does not really make sense. In real-life people on-duty within the communication unit will not be called for the same problems than people on-duty within the technical service so it makes more sense to create separated on-duty tags IMHO. It seems to me it's a technical shortcut to avoid too many manual operations but I am not sure it maps a functional reality.

However, I see a more generic application of this to filter the target groups or tags according to a given pattern, eg containing the keyword "on-duty".

**Comment by kazemar** [comment] 2021-08-31 12:54
Yes I understand. And each group manager should manage his own crew on-duty team members.
I close this issue

**Comment by claustres** [comment] 2021-08-31 12:57
I close it to reopen a dedicated issue about filtering groups/tags when the need will be more clear. For instance

**Closed by claustres** 2021-08-31 12:57 UTC
