### ISSUE TITLE
Tiled mesh layers not correctly unloaded when data is not available

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#150] opened 2020-05-13 18:03 UTC
Activate a tiled mesh layer like temperature or wind at a time with available data, then switch outside the data availability time range => previous data remains displayed although the current time does not match it.

**Comment by robinbourianes-frizko** [comment] 2020-05-14 15:07
Fixed with [this](https://github.com/kalisio/kdk/commit/3a9c68c972619b1e60eac875847bf28bf2a28a11)
I couldn't reproduce for tiled mesh layers like temperature, gust and such, only tiled wind layer.

**Closed by robinbourianes-frizko** 2020-05-14 15:07 UTC
Labels: bug, map
